### ISSUE TITLE
Armor Ordering...

### ISSUE THREAD

**Issue by CandleStormz** [Gobluebro/Elden-Ring-Checklist#88] opened 2024-07-26 11:17 UTC
I'm glad Armor got added but boi is it hard to find pieces. I am pretty sure it's ordered by weight or in game sections, though it's hard to tell.

I recommend ordering it alphabetically. The current ordering system is so time consuming to use that I don't think I will use it unless or until it's ordering is changed.

Anyway thank y'all for your hard work, I really appreciate it 😁

**Comment by Gobluebro** [comment] 2024-07-26 12:03
It is ordered by weight, though I imagine weights that are the same as each other don't match completely 100% as it does in the game. 

Feel free to provide screenshots of the correct in game order for weight and I will make the change.

There is no alphabetical order in the game so that doesn't seem like a better solution

**Comment by CandleStormz** [comment] 2024-07-28 03:40
The ordering of items is only follows the in game ordering half the time. Sure Spirit Ashes are in in-game order but Talismans are alphabetically sorted. 

It seems like, from my experience, using this checklist is easiest when it's alphabetical. For example, it's really easy to find a new talisman that I pick up because I can quickly and easily go to the letter.

Plus if armor is sorted by weight, many armors weigh the same and it seems like from my testing that it often fluctuates and switches the order after every sort

Therefore, alphabetical seems to make the most sense.

**Comment by Gobluebro** [comment] 2024-07-28 17:41
> Sure Spirit Ashes are in in-game order but Talismans are alphabetically sorted.

This was not selected as the final decision for sort order, this is more due to having a preference of adding content to the website as fast as possible was a better option than not having content on the website. I agree the talismans should be changed. I don't think weight feels the best since things like [Crimson Amber Medallion](https://eldenring.wiki.fextralife.com/Crimson+Amber+Medallion) regular, +1, +2 have a weight of 0.3 but then +3 has a weight of 0.6. I much prefer the sort by Item type as provided in game but that sort order is specifically a hidden type inside of the game's code that I don't have access to. So alphabetical was the "good enough for now" choice.

> from my experience, using this checklist is easiest when it's alphabetical. For example, it's really easy to find a new talisman that I pick up because I can quickly and easily go to the letter.

This is your specific use case and I get that. You could also just as easily use your browser's "[Find in Page](https://www.howtogeek.com/671304/how-to-quickly-search-for-text-on-the-current-web-page/)" feature to search for the newly acquired item of yours. The "Collapse/Open All" button on the website was made for because of previous users using the Find in Page feature.

However, for someone using the website to double check if they did everything at the end of their play through this use case is time consuming for them. They would have to find every item instead of just easily swapping back and forward between the site and the game. Matching items to where they exist in game also provides fast feedback of things you are missing instead of having to make sure you input everything onto the website first.

> Plus if armor is sorted by weight, many armors weigh the same and it seems like from my testing that it often fluctuates and switches the order after every sort

In my testing I have not found that to be the case. I have found that sorting will remain consistent when changing sorts. Do you mean item order changes after acquiring new items? I would find that to be correct behavior as you are getting an item that wasn't in the previous sort to begin with.

**Comment by Gobluebro** [comment] 2024-07-28 17:45
I will be closing this issue as I am going to be keeping this sort order as weight for the time being. Maybe some other repos are providing these in game sort orders that I have just not found yet. I will look into finding something that works for the experience I'm trying to provide on this website. 

If you have in game screen shots of a correct sort order of item weight that doesn't match on the website feel free to open this issue again or create a new one. As long as there is some screenshots then I can confirm it and make the change to the website.

**Closed by Gobluebro** 2024-07-28 17:45 UTC
Labels: documentation

**Comment by Gobluebro** [comment] 2024-07-30 03:30
Armors now sorted in Item Type order.
Checked against in game with all armors and removed all currently unavailable armors that existed previously in the lists.
