### ISSUE TITLE
Elden Ring checklist (Greataxes) 

### ISSUE THREAD

**Issue by sojin0123** [Gobluebro/Elden-Ring-Checklist#94] opened 2024-08-12 03:52 UTC
Hello, Goodafternnon.
 So I was trying to complete my checklist and in the great axe area the weapon ''Sacred Butchering Knife'' is no where to be find. 
I try to find in different section but I still can't find it, I don't know if this an issue or not but please let me me know where to find it. Thank you.

**Comment by Gobluebro** [comment] 2024-08-12 21:30
duplicate of https://github.com/Gobluebro/Elden-Ring-Checklist/issues/80#issuecomment-2212855166

**Comment by Gobluebro** [comment] 2024-08-12 21:30
> This is labeled as Butchering Knife because depending on the infusion of the weapon, the name changes. If you infused it with Keen it would become the Keen Butchering Knife instead. https://eldenring.wiki.fextralife.com/Butchering+Knife The weapon comes pre-infused with Sacred enhancement.

**Closed by Gobluebro** 2024-08-12 21:30 UTC
